### PR TITLE
Update generic structures for topology graphs using single atom representations.

### PR DESCRIPTION
**Pull request by andrewtarzia**
Related Issues: #431 
Requested Reviewers: @lukasturcani 

This PR aims to improve the representation of topology graphs by removing artificial chemistry and focussing on the assignment and connectivity of vertices. Hopefully this improves website load times and accessibility to users. All changes are made in the doc strings, and small changes to readability are also attempted for all topology graphs.

- [ ] Add UNICODE colour maps between vertices and text.
- [ ] Finish cages
- [ ] Do for COFs
- [ ] Do for examples of macrocycles, host_guests, complexes and polymers.

### CODE REVIEW

**Comment by lukasturcani** [comment]
1. do you think it is preferable to have the linkers straight?
image

**Comment by lukasturcani** [comment]
Other than that -- barring the change from `COLOR1` and `COLOR2` into some kind of color unicode square (if possible) -- LGTM

**Review by lukasturcani — CHANGES_REQUESTED** [review]
LGTM bar comments above

**Comment by andrewtarzia** [comment]
> 1. do you think it is preferable to have the linkers straight?
>    image

So, the vertices are a single bead, which means that if there is a 'bend' it is because of the geometry of the input topology graph.

This is actually most clear in the M24L48 topology graph, where I clearly did not get the math right on the vertex positions. A negligible effect when the building blocks are full chemical structures though.

image

**Comment by lukasturcani** [comment]
Interesting -- i guess leave it then? I assume we dont wanna mess with the topology graph vertices

**Comment by lukasturcani** [comment]
Also -- for me -- i do like the fact  that there was a non-abstract example of a real cage. It kind of felt more "real" to me. Do you think having both a real and an abstract example is worthwhile? Is it worth checking with other peeps which representation they would find most useful?

**Comment by andrewtarzia** [comment]
> Interesting -- i guess leave it then? I assume we don't wanna mess with the topology graph vertices
I actually intend to fix this in the future, because ultimately, these small changes will not effect people's work because geometry optimisations should be done after. But future versions should have more symmetrical inputs, it just makes more sense to me.



> Also -- for me -- i do like the fact that there was a non-abstract example of a real cage. It kind of felt more "real" to me. Do you think having both a real and an abstract example is worthwhile? Is it worth checking with other peeps which representation they would find most useful?

I think both have their place, but having both may be too much.  Perhaps we ask the discord, and maybe you can ask people in the Jelfs group?

**Comment by andrewtarzia** [comment]
Also, I think the ball and stick mode reminds users that they are not limited to any particular chemistry.

**Comment by lukasturcani** [comment]
Yeah -- go ahead and ask on discord and I will press people in person when I see them

**Comment by andrewtarzia** [comment]
Based on discussions with others, and difficulty in making useful maps between vertex number and atom colours, I have decided to close this PR and issue.

**Pull request closed without merging**
