### PR TITLE
handle UTF-8 encoding on windows

### LINKED ISSUE #43: XTBExtractor test not working on Windows
Some character in the xtb extraction cannot be read.

```================================================================================================= FAILURES =================================================================================================
____________________________________________________________________________________________ test_xtb_extractor ____________________________________________________________________________________________

    def test_xtb_extractor():
        known_output_file = join('../data', 'xtb_energy.output')
    
        # Get properties from output_file.
>       xtbext = stk.XTBExtractor(output_file=known_output_file)

..\test_utilities.py:10:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\stk\utilities\utilities.py:1281: in __init__
    self.output_lines = f.readlines()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <encodings.cp1252.IncrementalDecoder object at 0x000002D9C98866A0>
input = b'\n         #    Occupation            Energy/Eh            Energy/eV\r\n      --------------------------------------...C   40 0.952\r\n    45  H   1.000        C   40 0.960\r\n    46  H   0.997
      C   41 0.977\r\n    47  H   0.997   '
final = False

    def decode(self, input, final=False):
>       return codecs.charmap_decode(input,self.errors,decoding_table)[0]
E       UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5367: character maps to <undefined>

encodings\cp1252.py:23: UnicodeDecodeError
============================================================================ 1 failed, 116 passed, 11 skipped in 22.42 seconds =============================================================================```

### PR DESCRIPTION
**Pull request by andrewtarzia**
Fixes #43

### CODE REVIEW

**Comment by lukasturcani** [comment]
Why does it fix it? I think a comment in the code would also be useful.

**Comment by andrewtarzia** [comment]
I believe you are correct and I added the comment. The only way to know for sure is when @fiszczyp checks the code because I do not have a Windows machine.

**Comment by fiszczyp** [comment]
Tests pass now.

**Comment by andrewtarzia** [comment]
This PR will be closed because of a merge to newer versions of stk which caused overlap. It will be reopened.

**Pull request closed without merging**
