### PR TITLE
Normalising rotation matrices

### PR DESCRIPTION
**Pull request by andrewtarzia**
This is fix for #184. Handles the issue by ensuring all rotation matrices are normalised using scipy Rotation class.

In future (an enhancement), I would think we could use that class to take a rotation matrix, and output a quaternion (not limited to this, but this is my first guess) for stable molecule manipulation.

### CODE REVIEW

**Comment by andrewtarzia** [comment]
To solve the issue with this test (1 molecule (metal_cage_m4l6_tetrahedron-metal_cage_m4l6_tetrahedron0) failing the get_plane_normal test for two random atom_id inputs, which passed on multiple local Ubuntu machines), I have changed the molecule that is failing to a different molecule based on the input building blocks.

**Comment by lukasturcani** [comment]
How come the iron complex was replaced with the fake complex?

**Review by lukasturcani — APPROVED** [review]

**Review by lukasturcani — CHANGES_REQUESTED** [review]
Can confirm that this fix works, tyvm!. Just one thing: could you add the molecule which caused the issue in https://github.com/lukasturcani/stk/issues/184 as a test case? And when you do, add a little comment above it which says something along the lines of "See https://github.com/lukasturcani/stk/issues/184"

**Comment by lukasturcani** [comment]
Retracting my previous comment because the issue is visible in an existing test case.

**Pull request merged**
